# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleSource', models.CharField(max_length=200, null=True)),
                ('sourceType', models.CharField(max_length=200, null=True)),
                ('pubDate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('isbn', models.CharField(max_length=200, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopusId', models.BigIntegerField(default=True, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('article', models.ManyToManyField(related_name='authors', to='testParse.Article')),
            ],
        ),
        migrations.CreateModel(
            name='IdKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testParse.Article')),
            ],
        ),
    ]
