# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spinId', models.IntegerField(null=True)),
                ('scopusIdentifier', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(max_length=200, null=True)),
                ('wosUid', models.CharField(max_length=200, null=True)),
                ('sourceType', models.CharField(max_length=200, null=True)),
                ('pubDate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('isbn', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopusId', models.BigIntegerField(default=True, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('article', models.ManyToManyField(related_name='authors', to='testParse.Article')),
            ],
        ),
    ]
